import Link from "next/link";
import { Navigation } from "./Components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";
import { Space_Grotesk } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const font = Space_Grotesk({
  weights: ['400'],
  preload: false,
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        
      <body className={font.className}>
      <h1>My Next app</h1>
        <Navigation />
        {children}
        
      </body>
    </html>
  );
}
